/**
 * List all Action types used in the application
 */

export default {

  LISTEN_WEBSOCKET:     'LISTEN_WEBSOCKET',
  HANDLE_WEBSOCKET:     'HANDLE_WEBSOCKET',

  LOGIN:                'LOGIN',
  SET_BALANCES:         'SET_BALANCES',
  SET_JOINEDCASES:      'SET_JOINEDCASES',
  SET_TRANSFERS:        'SET_TRANSFERS',
  SET_AUTH:             'SET_AUTH',

  // Cases
  FETCH_CASES:          'FETCH_CASES',
  SET_CLAIMANT_CASES:            'SET_CLAIMANT_CASES',
  SET_RESPONDANT_CASES:            'SET_RESPONDANT_CASES',
  SET_SELECTED_CASE:    'SET_SELECTED_CASE',
  FILE_CASE:            'FILE_CASE',
  DELETE_CASE:          'DELETE_CASE',
  ADD_CLAIM:            'ADD_CLAIM',
  DELETE_CLAIM:         'DELETE_CLAIM',
  READY_CASE:           'READY_CASE',
  RESPOND_CLAIM:           'RESPOND_CLAIM',

  // Claims
  SET_CLAIMS:        'SET_CLAIMS',
  FETCH_CLAIMS:      'FETCH_CLAIMS',
  SET_SELECTED_CLAIM:'SET_SELECTED_CLAIM',

  // Arbitrators
  SET_ARBITRATORS:  'SET_ARBITRATORS',
  FETCH_ARBITRATORS:'FETCH_ARBITRATORS',

  // UI
  SET_MEMBER_ACTION:          'SET_MEMBER_ACTION',
  SET_MEMBER_ACTION_LOADING:  'SET_MEMBER_ACTION_LOADING',

};
