/**
 * List all Action types used in the application
 */

export default {

  LISTEN_WEBSOCKET:     'LISTEN_WEBSOCKET',
  HANDLE_WEBSOCKET:     'HANDLE_WEBSOCKET',

  LOGIN:                'LOGIN',
  LOGOUT:               'LOGOUT',
  SET_BALANCES:         'SET_BALANCES',
  SET_JOINEDCASES:      'SET_JOINEDCASES',
  SET_TRANSFERS:        'SET_TRANSFERS',
  SET_AUTH:             'SET_AUTH',

  // Cases
  FETCH_CASES:          'FETCH_CASES',
  SET_CLAIMANT_CASES:   'SET_CLAIMANT_CASES',
  SET_RESPONDANT_CASES: 'SET_RESPONDANT_CASES',
  SET_ARBITRATOR_CASES: 'SET_ARBITRATOR_CASES',
  SET_SELECTED_CASE:    'SET_SELECTED_CASE',
  FILE_CASE:            'FILE_CASE',
  DELETE_CASE:          'DELETE_CASE',
  SHRED_CASE:           'SHRED_CASE',
  ADD_CLAIM:            'ADD_CLAIM',
  DELETE_CLAIM:         'DELETE_CLAIM',
  READY_CASE:           'READY_CASE',
  SUBMIT_CASEFILE:      'SUBMIT_CASEFILE',
  RESPOND_CLAIM:        'RESPOND_CLAIM',

  // Claims
  SET_CLAIMS:           'SET_CLAIMS',
  FETCH_CLAIMS:         'FETCH_CLAIMS',
  SET_SELECTED_CLAIM:   'SET_SELECTED_CLAIM',
  REMOVE_CLAIM:         'REMOVE_CLAIM',

  // Arbitrators
  SET_ARBITRATORS:       'SET_ARBITRATORS',
  FETCH_ARBITRATORS:     'FETCH_ARBITRATORS',

  // Modal
  SET_ACTION:          'SET_ACTION',
  SET_ACTION_LOADING:  'SET_ACTION_LOADING',
  SET_ACTION_ERROR:  'SET_ACTION_ERROR',
  EXECUTE_ACTION:  'EXECUTE_ACTION',

};
