/**
 * List all decisions classes
 */

export default {

  1: 'UNDECIDED',
  2: 'LOST KEY RECOVERY',
  3: 'TRX REVERSAL',
  4: 'EMERGENCY INTER',
  5: 'CONTESTED OWNER',
  6: 'UNEXECUTED RELIEF',
  7: 'CONTRACT BREACH',
  8: 'MISUSED CR IP',
  9: 'A TORT',
  10: 'BP PENALTY REVERSAL',
  11: 'WRONGFUL ARB ACT',
  12: 'ACT EXEC RELIEF',
  13: 'WP PROJ FAILURE',
  14: 'TBNOA BREACH',
  15: 'MISC',

};
